### ISSUE TITLE
"rumorCode":"K1CaO8wpc7Kwm"信息格式有误？

### ISSUE THREAD

**Issue by ghost** [thunlp/rumors#3]
"rumorCode":"K1CaO8wpc7Kwm"信息格式有误， informerUrl后面的数据格式错误
。
![_20181115101930](https://user-images.githubusercontent.com/15543855/48525737-28c27e80-e8c0-11e8-8a2d-7cde0b6a8879.png)

**Comment by tucunchao** [comment]
已修正
